language: python

python:
  - "3.6"

install:
  - pip3 install -r requirements.txt
  - pip install .
  - pip install pytest && pip install pytest-cov
  - pip install codecov

script:
  - ./runtests --cov

after_success:
  - codecov
